import json
from pathlib import Path


def _example_value(prop: dict) -> str:
    """Return a Python literal string for a given property schema."""
    t = prop.get("type", "string")
    if t == "string":
        return '"test_value"'
    if t in ("integer", "number"):
        return "1"
    if t == "boolean":
        return "True"
    if t in ("object", "array"):
        return "{}"
    return '"test_value"'


def _build_example_body(request_body: dict | None) -> str:
    """Build a dict literal string from a request body schema."""
    if not request_body or request_body.get("type") != "object":
        return "None"
    props = request_body.get("properties", {})
    required = request_body.get("required", [])
    items = []
    for name, prop in props.items():
        val = _example_value(prop)
        items.append(f'    "{name}": {val}')
    return "{\n" + ",\n".join(items) + "\n}"


def _sanitize(name: str) -> str:
    """Convert an operation or path string to a valid Python identifier fragment."""
    return name.replace("/", "_").replace("{", "").replace("}", "").replace("-", "_").strip("_")


def generate_tests(endpoints: list[dict], base_url: str, output_path: str) -> dict:
    """Generate a pytest file from parsed endpoints. Returns stats."""
    lines = [
        "# Auto-generated by API Dev Dashboard — do not edit manually",
        "import httpx",
        "import pytest",
        "",
        f'BASE_URL = "{base_url}"',
        "",
    ]

    test_count = 0
    endpoints_covered = set()

    for ep in endpoints:
        path: str = ep["path"]
        method: str = ep["method"]
        path_params: list = ep.get("path_params", [])
        request_body = ep.get("request_body")
        tag = ep.get("tag", "")
        sanitized = f"{method.lower()}_{_sanitize(path)}"

        # Resolve path with example values for happy path
        resolved_path = path
        for pp in path_params:
            resolved_path = resolved_path.replace("{" + pp["name"] + "}", "test_id_001")

        body_literal = _build_example_body(request_body)
        has_body = request_body is not None

        # Happy path
        lines += [
            f"def test_{sanitized}_happy_path():",
            f'    """{method} {path} — happy path"""',
        ]
        if method in ("POST", "PUT", "PATCH") and has_body:
            lines += [
                f"    payload = {body_literal}",
                f'    response = httpx.{method.lower()}(f"{{BASE_URL}}{resolved_path}", json=payload, timeout=10)',
            ]
        else:
            lines += [
                f'    response = httpx.{method.lower()}(f"{{BASE_URL}}{resolved_path}", timeout=10)',
            ]
        lines += [
            "    assert response.status_code < 500",
            "",
        ]
        test_count += 1

        # Validation error (only for endpoints with a request body)
        if method in ("POST", "PUT", "PATCH") and has_body:
            lines += [
                f"def test_{sanitized}_validation_error():",
                f'    """{method} {path} — missing required fields, expects 422"""',
                f'    response = httpx.{method.lower()}(f"{{BASE_URL}}{resolved_path}", json={{}}, timeout=10)',
                "    assert response.status_code == 422",
                "",
            ]
            test_count += 1

        # Not found (only for endpoints with path params)
        if path_params and method in ("GET", "PUT", "PATCH", "DELETE"):
            not_found_path = path
            for pp in path_params:
                not_found_path = not_found_path.replace("{" + pp["name"] + "}", "nonexistent_id_99999")
            lines += [
                f"def test_{sanitized}_not_found():",
                f'    """{method} {path} — unknown ID, expects 404"""',
                f'    response = httpx.{method.lower()}(f"{{BASE_URL}}{not_found_path}", timeout=10)',
                "    assert response.status_code == 404",
                "",
            ]
            test_count += 1

        endpoints_covered.add(f"{method} {path}")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")

    return {
        "file_path": output_path,
        "test_count": test_count,
        "endpoints_covered": len(endpoints_covered),
    }
